### ISSUE TITLE
diasmbiguation of same name individual

### ISSUE THREAD

**Issue by anthonymobile** [KordingLab/nsfcoa-app#4]
This has long been a problem for me, as there is another scholar with the same name and middle initial. "Anthony M Townsend". thoughts on how to address?

**Comment by j6k4m8** [comment]
Thanks for reporting, @anthonymobile! I'd love too add functionality to search by ORCID (or even OpenAlex ID), a la #2... basically bypassing the [search/lookup code](https://github.com/KordingLab/nsfcoa-app/blob/main/server.py#L32) and directly getting works by OpenAlex ID, or searching by ORCID first...
https://github.com/j6k4m8/openalex/blob/main/openalex/__init__.py#L252

I think it's a relatively easy edit, just haven't had the occasion yet. I'll bump it up on my todo list and will keep you updated!!

**Comment by j6k4m8** [comment]
actually @anthonymobile — never mind, I just fixed it. should take an ORCID now! i.e., [0000-0001-6618-0794](https://orcid.org/0000-0001-6618-0794)

**Comment by j6k4m8** [comment]
please reopen if you're still having issues of course!!
